version: '3.8'

services:
    php-cli:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-cli
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
